CSV_PATH = "data/ted_talks_en.csv"
PICKLE_PATH = 'data/cleaned_data.pkl'
PICKLE_PATH_TITLE = 'data/cleaned_data_title.pkl'
BEST_THRESHOLD_PATH = "models/best_thresholds.npy"
BEST_THRESHOLD_PATH_TITLE = "models/best_thresholds_title.npy"

MINIMUM_TOPIC_APPEARANCE = 50
MAX_TOKENS_LENGTH = 8000

TED_TOPICS = ['ai', 'africa', 'dna', 'internet', 'planets', 'united states', 'activism', 'adventure', 'aging', 'agriculture', 'algorithm', 'ancient world', 'animals', 'animation', 'architecture', 'art', 'astronomy', 'beauty', 'big problems', 'biodiversity', 'biology', 'biotech', 'books', 'brain', 'business', 'cancer', 'chemistry', 'children', 'choice', 'cities', 'climate change', 'cognitive science', 'collaboration', 'comedy', 'communication', 'community', 'compassion', 'computers', 'creativity', 'crime', 'culture', 'data', 'death', 'decision making', 'demo', 'democracy', 'design', 'disease', 'ecology', 'economics', 'education', 'emotions', 'energy', 'engineering', 'entertainment', 'entrepreneur', 'environment', 'evolution', 'exploration', 'family', 'feminism', 'film', 'food', 'future', 'gender', 'gender equality', 'genetics', 'global development', 'global issues', 'government', 'green', 'happiness', 'health', 'health care', 'healthcare', 'history', 'human body', 'humanity', 'humor', 'identity', 'illness', 'india', 'inequality', 'infrastructure', 'innovation', 'insects', 'intelligence', 'invention', 'journalism', 'language', 'law', 'leadership', 'life', 'literature', 'live music', 'love', 'math', 'media', 'medical research', 'medicine', 'memory', 'mental health', 'mind', 'money', 'motivation', 'music', 'nature', 'neuroscience', 'oceans', 'parenting', 'peace', 'performance', 'personal growth', 'philosophy', 'photography', 'physics', 'physiology', 'poetry', 'policy', 'politics', 'pollution', 'potential', 'poverty', 'product design', 'psychology', 'public health', 'race', 'relationships', 'religion', 'robots', 'science', 'self', 'sex', 'social change', 'social media', 'society', 'software', 'space', 'storytelling', 'success', 'sustainability', 'teaching', 'technology', 'universe', 'violence', 'visualizations', 'war', 'water', 'women', 'work', 'world cultures', 'writing', 'youth']
MN_DS_CLASSIFY_NEW_LABELS = {
"accident": [], "accomplishment": ["success"], "act of terror": ["violence", "crime"], "animal": ["animals"], "anniversary": [], "armed conflict": ["war", "violence"], "arts": ["art", "culture"], "belief": ["religion", "philosophy"], "biomedical science": ["health", "science", "medicine"], "bodybuilding": ["human body"], "business information": ["business"], "ceremony": ["community", "culture"], "civil unrest": ["activism", "violence", "politics", "social change"], "communities": ["society", "community"], "competition discipline": [], "conditions": [], "conflict": [], "conservation": ["environment", "nature"], "coup d'etat": ["war", "government", "politics"], "demographics": ["society"], "disaster": [], "disciplinary action in sport": [], "discrimination": ["inequality"], "diseases": ["disease", "health"], "drug use in sport": ["health"], "economic sector": ["business", "economics"], "economy": ["money", "economics"], "election": ["politics", "democracy"], "emergency incident": [], "emergency planning": ["policy"], "emergency response": ["policy"], "emigration": [ "global issues"], "employment": ["work"], "employment legislation": ["work", "law", "policy"], "environmental politics": ["environment", "politics"], "environmental pollution": ["environment", "pollution", "climate change"], "exchange": [], "exercise": [], "finance": ["money"], "fitness": ["human body", "health"], "fundamental rights": [ "law"], "government policy": ["government", "politics", "policy"], "health facility": ["health", "health care"], "health organisations": ["health", "health care", "public health"], "health treatment": ["health", "health care", "medicine"], "healthcare policy": ["health care", "policy"],
"human interest": ["humanity"], "immigration": [ "global issues"], "international relations": [], "interreligious dialogue": ["religion", "communication"], "judiciary": [ "law"], "justice": [], "labour": ["work"], "labour market": ["work", "economics"], "labour relations": ["work"], "law enforcement": ["government", "law", "crime"], "learning": ["education"], "leisure": [], "lifestyle": ["life" ], "mankind": ["humanity"], "market": ["business"], "mass media": ["media"], "massacre": ["war", "violence", "crime"], "mathematics": ["science", "math"], "medical profession": ["work", "health", "health care"], "natural resources": ["environment", "nature"], "natural science": ["nature", "science"], "non governmental organisation": [ "activism", "community"], "non human diseases": ["animals", "disease"], "parent organisation": [], "peace process": ["peace"], "people": ["society", "humanity"], "plant": ["biology", "nature"], "political crisis": ["government", "politics"], "political dissent": ["social change", "politics", "activism"],
"political process": [ "politics"], "post war reconstruction": ["war", "infrastructure"], "prisoners of war": ["war"], "religious belief": ["religion"], "religious conflict": ["religion"], "religious education": ["religion", "education"], "religious event": ["religion","culture"], "religious facilities": ["religion"], "religious institutions": ["religion"], "religious leader": ["religion", "leadership"], "religious text": ["religion"], "retirement": ["work", "aging"], "school": ["education"], "scientific institution": ["education", "science"], "scientific research": ["science", "innovation"], "scientific standards": ["science"], "social condition": [], "social learning": ["education", "society"], "social problem": ["social change", "society", "big problems"], "social sciences": ["society", "science"], "sport": [], "sport event": [], "sport industry": ["entertainment", "business"], "sport organisation": [], "sport venue": ["architecture", "infrastructure"], "state relations": ["government", "politics"], "transfer": [],
"unemployment": ["work", "economics"],
"unions": ["work", "society"], "values": [], "vocational education": ["work", "education"], "weather": ["environment", "climate change"], "weather forecast": ["environment", "climate change"], "weather phenomena": ["environment", "climate change"], "weather statistic": ["environment", "climate change", "data"], "weather warning": ["environment", "climate change"], "welfare": []
}

REPO_ID_DATASET = "Naftali1996/Datasets"
